runtime: custom
env: flex

env_variables:
  DJANGO_SETTINGS_MODULE: 'myproject.settings'
  PYTHONUNBUFFERED: 1
  DEBUG: False
  ALLOWED_HOSTS: '*'
  GOOGLE_CLOUD_PROJECT: 'personal-website-395618'
  CSRF_TRUSTED_ORIGINS: 'https://personal-website-395618.uc.r.appspot.com,https://personal-website-395618.appspot.com,https://boltml-686910583227.us-central1.run.app,https://boltml.onrender.com'
  USE_X_FORWARDED_HOST: 'True'
  USE_X_FORWARDED_PORT: 'True'

handlers:
- url: /static
  static_dir: staticfiles
  secure: always

- url: /.*
  script: auto
  secure: always

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.65