runtime: custom
env: flex

env_variables:
  DJANGO_SETTINGS_MODULE: 'myproject.settings'
  PYTHONUNBUFFERED: 1
  DEBUG: False
  ALLOWED_HOSTS: '*'
  GOOGLE_CLOUD_PROJECT: 'personal-website-395618'
  CSRF_TRUSTED_ORIGINS: 'https://personal-website-395618.uc.r.appspot.com,https://personal-website-395618.appspot.com,http://127.0.0.1:8000,https://bolt-ml.com,https://www.bolt-ml.com'
  USE_X_FORWARDED_HOST: 'True'
  USE_X_FORWARDED_PORT: 'True'
  GA_TRACKING_ID: 'G-P488NT9NQC'
  DATABASE_URL: 'postgresql://postgres.fcyudwcpuofaqukydpnd:Longasspassword22374!@aws-0-us-west-1.pooler.supabase.com:6543/postgres'

handlers:
- url: /static
  static_dir: staticfiles
  secure: always

- url: /myapp/models
  static_dir: myapp/models
  secure: always

- url: /.*
  script: auto
  secure: always

resources:
  cpu: 2
  memory_gb: 2.0
  disk_size_gb: 20

automatic_scaling:
  target_cpu_utilization: 0.65
  min_num_instances: 2
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.65
    
readiness_check:
  app_start_timeout_sec: 300
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  
liveness_check:
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

network:
  session_affinity: true