# Generated by Django 4.2.17 on 2025-02-02 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
